Nargiza/string1
nuta312/CodingBatWinter24 pull request #39
Opened 2024-05-17 06:18 UTC by NargizaKudaibergenova

2024-05-17 06:38 UTC, NargizaKudaibergenova commented
Please check the code!

2024-05-17 09:48 UTC, Aseinova93 commented
Great job!

2024-05-17 09:49 UTC, Aseinova93 approved these changes

2024-05-17 09:49 UTC, Aseinova93 approved these changes

2024-05-17 09:52 UTC, Aseinova93 requested changes

2024-05-17 09:52 UTC, Aseinova93 commented on src/main/java/com/digital_nomads/nargiza/string1/ComboString.java
> +    public String comboString(String a, String b) {
Наргиза, у вас все прекрасно, просто для практики пишу))

2024-05-17 09:57 UTC, Aseinova93 approved these changes

2024-05-17 09:57 UTC, Aseinova93 commented on src/main/java/com/digital_nomads/nargiza/warmup1/SleepIn.java
> +        if (!weekday || vacation) {
cool!

2024-05-17 15:47 UTC, Aseinova93 approved these changes

2024-05-17 16:00 UTC, Aik1986 commented
исправить ошибку! 
<<<<<<< nargiza/String1
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
=======
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
>>>>>>> master

2024-05-17 16:01 UTC, Aik1986 commented
исправить ошибку!
<<<<<<< nargiza/String1
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
=======
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
>>>>>>> master

2024-05-17 16:41 UTC, Zhakutay commented on src/main/java/com/digital_nomads/nargiza/string1/ComboString.java
> +    public String comboString(String a, String b) {
Привет Наргиза,

При попытке слить вашу ветку `Nargiza/string1` с `master` возникли конфликты в следующих файлах:
- pom.xml
- src/main/java/com/digital_nomads/nargiza/string1/HelloName.java

Пожалуйста, разрешите конфликты локально.

Если возникнут вопросы, обращайтесь.

2024-05-19 15:24 UTC, Aik1986 approved these changes

2024-05-19 18:14 UTC, Aykesha commented
Good job!!!

2024-05-19 18:20 UTC, Aykesha commented
Ошибки попробовала исправить! Удачи!

2024-05-19 18:20 UTC, closed without merging